// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3AdCw7k4KrEoTxFwNSi_mig6g1YXPI-8',
    appId: '1:974455309607:web:f4879d0b99fbd691b45502',
    messagingSenderId: '974455309607',
    projectId: 'loginregister-d9eaf',
    authDomain: 'loginregister-d9eaf.firebaseapp.com',
    storageBucket: 'loginregister-d9eaf.firebasestorage.app',
    measurementId: 'G-0F4QGNN78W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qlcrDBoQUm9eDhhpFs-19gmdMBzm-nY',
    appId: '1:974455309607:android:d2a4e4b4250f0667b45502',
    messagingSenderId: '974455309607',
    projectId: 'loginregister-d9eaf',
    storageBucket: 'loginregister-d9eaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIQnbCI5uCmFlptuiLdiWlBjhOKRUMhhM',
    appId: '1:974455309607:ios:1370f112c346b0bcb45502',
    messagingSenderId: '974455309607',
    projectId: 'loginregister-d9eaf',
    storageBucket: 'loginregister-d9eaf.firebasestorage.app',
    iosBundleId: 'com.example.wastewise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIQnbCI5uCmFlptuiLdiWlBjhOKRUMhhM',
    appId: '1:974455309607:ios:1370f112c346b0bcb45502',
    messagingSenderId: '974455309607',
    projectId: 'loginregister-d9eaf',
    storageBucket: 'loginregister-d9eaf.firebasestorage.app',
    iosBundleId: 'com.example.wastewise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3AdCw7k4KrEoTxFwNSi_mig6g1YXPI-8',
    appId: '1:974455309607:web:2819f8fa07a0a9f2b45502',
    messagingSenderId: '974455309607',
    projectId: 'loginregister-d9eaf',
    authDomain: 'loginregister-d9eaf.firebaseapp.com',
    storageBucket: 'loginregister-d9eaf.firebasestorage.app',
    measurementId: 'G-R43XZSRBC0',
  );
}
